<?php

namespace App\Console\Commands;

use App\Models\Tenant;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Str;
use Stancl\Tenancy\Database\Models\Domain;

class TenantCreateCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'tenant:create 
                            {name : The name of the tenant organization}
                            {domain : The domain/subdomain for the tenant}
                            {--email= : Email for the initial admin user}
                            {--password= : Password for the initial admin user (will be generated if not provided)}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Create a new tenant with database, migrations, and initial admin user';

    /**
     * Execute the console command.
     */
    public function handle(): int
    {
        $name = $this->argument('name');
        $domain = $this->argument('domain');
        $email = $this->option('email') ?? $this->ask('Enter email for initial admin user');
        $password = $this->option('password') ?? Str::random(16);

        $this->info("Creating tenant: {$name} ({$domain})");

        try {
            // Step 1: Create tenant (UUID is auto-generated by stancl/tenancy)
            $this->info('Step 1: Creating tenant record...');
            $tenant = Tenant::create([
                'id' => Str::uuid()->toString(),
                'data' => [
                    'name' => $name,
                    'created_by' => 'system',
                ],
            ]);

            $this->info("✓ Tenant created with ID: {$tenant->id}");

            // Step 2: Create domain (this triggers database creation via events)
            $this->info('Step 2: Creating domain and database...');
            // Extract subdomain from full domain (e.g., 'test' from 'test.localhost')
            $subdomain = explode('.', $domain)[0];
            Domain::create([
                'domain' => $subdomain, // Save only the subdomain part
                'tenant_id' => $tenant->id,
            ]);

            $this->info("✓ Domain '{$domain}' created");
            $this->info('✓ Database creation and migrations triggered automatically');

            // Wait a moment for async jobs if they're queued
            // In our case, they're not queued (shouldBeQueued(false)), so they run synchronously
            sleep(2);

            // Step 3: Create initial admin user in tenant database
            $this->info('Step 3: Creating initial admin user...');
            
            $userId = null;
            $tenant->run(function () use ($email, $password, $name, &$userId) {
                // Seed roles and permissions first
                Artisan::call('db:seed', ['--class' => 'RolesAndPermissionsSeeder']);
                
                // Create user in tenant database
                $user = \App\Models\User::create([
                    'name' => 'Organization Owner',
                    'email' => $email,
                    'password' => Hash::make($password),
                    'email_verified_at' => now(),
                ]);

                // Assign Organization Owner role
                $user->assignRole('Organization Owner');
                $userId = $user->id;
            });
            
            $this->info("✓ Admin user created with ID: {$userId}");
            $this->info("✓ Organization Owner role assigned");

            // Step 4: Create storage directory for tenant
            $this->info('Step 4: Creating storage directory...');
            $storagePath = storage_path("app/tenants/{$tenant->id}");
            if (!is_dir($storagePath)) {
                mkdir($storagePath, 0755, true);
                $this->info("✓ Storage directory created: {$storagePath}");
            }

            // Step 5: Send credentials email (optional, can be implemented later)
            $this->info('Step 5: Credentials prepared...');
            $this->table(
                ['Field', 'Value'],
                [
                    ['Tenant ID', $tenant->id],
                    ['Name', $name],
                    ['Domain', $domain],
                    ['Admin Email', $email],
                    ['Admin Password', $password],
                ]
            );

            $this->warn('⚠️  Please save these credentials securely!');
            $this->warn('⚠️  Email functionality will be implemented in a later step.');

            $this->newLine();
            $this->info("✅ Tenant '{$name}' created successfully!");
            $this->info("   Access at: http://{$domain}");

            return Command::SUCCESS;
        } catch (\Exception $e) {
            $this->error("Failed to create tenant: {$e->getMessage()}");
            $this->error($e->getTraceAsString());
            return Command::FAILURE;
        }
    }
}
